# Generated by Django 5.2 on 2025-05-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carro_id', models.IntegerField()),
                ('desgaste_pneus', models.JSONField()),
                ('temperatura_pneus', models.JSONField()),
                ('temperatura_real', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clima', models.CharField(max_length=20)),
                ('temperatura_pista', models.IntegerField()),
                ('temperatura_ar', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telemetria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_piloto', models.CharField(max_length=100)),
                ('volta', models.IntegerField()),
                ('numero_carro', models.IntegerField()),
                ('tempo', models.FloatField()),
                ('posicao', models.IntegerField()),
                ('velocidade', models.FloatField()),
                ('tipo_pneus', models.CharField(max_length=20)),
            ],
        ),
    ]
